New icon: System76
aegis-icons/aegis-icons pull request #615
Opened 2022-06-18 01:51 UTC by groebnerbasis

Push System76 icon with best attempt to follow guidelines of Aegis Icons

**URL of the site:**
https://system76.com/

**Logo / icon info:**
This is the monochrome System76 logo from the System76 brand asset [repo](https://github.com/system76/brand/tree/master/System76%20branding).

- Direct URL of the logo file: https://github.com/system76/brand/blob/master/System76%20branding/system76-logo_secondary_cutout.svg
    - URL of System76 brand assets: https://github.com/system76/brand
- Short info of how did you get the logo: the logo is available on GitHub, though here by System76 on [Twitter](https://nitter.42l.fr/system76/status/1537851282500861953#m)

**Background color info:**
The brown used is from the [color swatch](https://github.com/system76/brand/blob/master/System76%20branding/system76_logos_CMYK.svg) for System76, which I obtained via the visual cursor selector in GColor2.

This brown is part of the brown, yellow, and white logo.

I was originally given the color logo on Twitter and obtained `#585048` from the [color logo]( https://github.com/system76/brand/blob/master/System76%20branding/system76-logo_secondary.svg), but then I obtained `#595149` from the color swatch above.

I decided to use `#595149` in the final logo.

- [X] I have carefully read and followed CONTRIBUTING document.

## Extra notes

The goldenrod yellow is `#FAA41A` from the color logo or `#F6AD1B` from the color swatch in GColor2 - this could be helpful if anyone wanted to make a darker yellow background variation of the logo in the future, but I am ok with just the brown background.

I used Inkscape on Arch Linux with the [SVG template](https://github.com/aegis-icons/aegis-icons/blob/master/_templates/svg_template.svg) and had to install `scour` from Pacman in order to make the "Optimized SVG" instructions work.

I also installed [`svgo`](https://aur.archlinux.org/packages/svgo) from the AUR in order to use the CLI post processing instructions, since this is the only npm package I currently need and the package itself updates infrequently.

Lastly, please read Inkscape's official documentation on [importing pictures](https://inkscape-manuals.readthedocs.io/en/latest/import-pictures.html) instead of wasting time reading third party sources from search engines - at least thank the [team](https://inkscape.org/*docs/) by putting their work to good use.

2022-06-18 17:22 UTC, krisu5 commented
> The brown used is from the [color swatch](https://github.com/system76/brand/blob/master/System76%20branding/system76_logos_CMYK.svg) for System76, which I obtained via the visual cursor selector in GColor2.
>This brown is part of the brown, yellow, and white logo.
>I was originally given the color logo on Twitter and obtained #585048 from the [color logo](https://github.com/system76/brand/blob/master/System76%20branding/system76-logo_secondary.svg), but then I obtained #595149 from the color swatch above.
>I decided to use #595149 in the final logo.

I don't why System76 converted vectors with CMYK colors to SVG (vector format that doesn't even support CMYK in the first place), but in a nutshell:

**CMYK colors are only meant for print, never for screen usage.** The convert to CMYK -> RGB (color system that screens use) almost always fails and isn't exactly same color anymore.

In the [Brand Book](https://system76.cdn.prismic.io/system76/81ae9b62-8848-450a-9fd3-5d6f4f0d1d5d_system76_brand-manual_2022.pdf) linked in [about page](https://system76.com/about), in page 20, the `Terra_Grey` brand color is `#574f4a`, **change the BG color to that instead!**

> I used Inkscape on Arch Linux with the [SVG template](https://github.com/aegis-icons/aegis-icons/blob/master/_templates/svg_template.svg) and had to install scour from Pacman in order to make the "Optimized SVG" instructions work.

I didn't know that you need to install scour too in Linux, I add that to the doc some day.

> I also installed [svgo](https://aur.archlinux.org/packages/svgo) from the AUR in order to use the CLI post processing instructions, since this is the only npm package I currently need and the package itself updates infrequently.

OK, it doesn't really matter if it's the same thing.

> Lastly, please read Inkscape's official documentation on [importing pictures](https://inkscape-manuals.readthedocs.io/en/latest/import-pictures.html) instead of wasting time reading third party sources from search engines - at least thank the [team](https://inkscape.org/*docs/) by putting their work to good use.

I don't know what this is about.

2022-06-18 17:29 UTC, krisu5 requested changes

2022-06-18 17:29 UTC, krisu5 commented on SVG/System76.svg
> +   <circle id="Background" cx="512" cy="512" r="512" style="fill:#595149"/>
- Remove `id="Background"`
- Change the `style="fill:#595149"` ➜ `style="fill:#574f4a"`

2022-06-18 17:29 UTC, krisu5 commented on SVG/System76.svg
> +   <path transform="matrix(.5 0 0 .5 256 256)" d="M983.79 312.91A515.15 515.15 0 0 0 805.02 92.23l-.007.018.05.035.157.11-1.452 4.385c-9.797 18.218-120.24 217.92-161.82 293.1l-2.005 3.624a40919.505 4
- Remove `transform="matrix(.5 0 0 .5 256 256)"`
- Change the `style="stroke-width:1.0286;fill:#fff"` ➜ `style="fill:#fff"`
- Remove space before `/>`

2022-07-10 20:00 UTC, krisu5 commented
Closing this as stale in a week if no response.

2022-08-19 15:38 UTC, krisu5 commented
Closed as stale.

2026-03-07 21:43 UTC, Goldmaster commented
This cannot be merged safely due to how out of date the fork has become and there does not seam to be any option to update your forked version with new changes. I have added system76 and as such closes the issue.

2026-03-07 21:43 UTC, closed without merging