New icon: Husky
aegis-icons/aegis-icons pull request #791
Opened 2022-12-29 00:31 UTC by joshcancode

- [X] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site:**
> [husky.io](https://husky.io/)

**Proof of the Aegis-compatible 2FA:**
> https://help.husky.io/pt-BR/articles/5979491-o-que-e-e-como-funciona-a-autenticacao-em-dois-fatores

**Logo / icon info:**
> [SVG from front page](https://uploads-ssl.webflow.com/62cc74ca475d041718de7fc2/62cc74ca475d041923de7ff4_husky-horizontal-logo.svg)

**Background color info:**
> The background color was a bit of an issue, I was torn on the color of the text, the average color of the icon or the button color on the main page, since there isn't a clear brand color. I settled on the average color of the logo, obtained using [this site](https://10015.io/tools/image-average-color-finder) set to the "Square Root" option. `#d92673`

This pull request is meant to close #790

2022-12-29 15:37 UTC, krisu5 requested changes
1. Change the BG to `#FF2155`, this is one of two colors in the logomark's middle section ([got with this method](http://miraimages.com/illustrator-gradient-colors-to-swatches/), also mentioned in [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#colors))
2. Use logomark, not text.

For logomark, create whitespace between "ears" and "face".

1. Scale the logomark for the icon first based of guides
2. Create outside going outline for "face" part (10pt is usually pretty good)
3. Path -> outline stroke
4. Ungroup the group that Illustrator just created
5. Select outlined stroke and ears
6. Pathfinder -> Divine
7. Remove the parts of outlined stroke, leaving the whitespace between ears and face.

2022-12-31 14:51 UTC, joshcancode commented
Sorry for the delay on these changes, ended up catching a cold and being off the PC a bit more.

Is there a way to extract these gradient colors without Illustrator? Thanks.

2022-12-31 15:33 UTC, krisu5 approved these changes

2022-12-31 15:44 UTC, krisu5 commented
> Sorry for the delay on these changes, ended up catching a cold and being off the PC a bit more.

No problem, I also had cold / covid :)

> Is there a way to extract these gradient colors without Illustrator? Thanks.

Yes there is, I should add that to CONTRIBUTING.

1. Either open SVG in text editor or browser (if in browser, use inspector tool or view source page)
2. Find `linearGradient` or `radialGradient` element
3. The `stop-color` values inside of the `linearGradient` / `radialGradient` element are the colors used in the gradient.

If there's multiple `linearGradient` / `radialGradient` elements, you'll need to check IDs and path fills for correct match.

But this method only works for SVGs, EPS and PDF work differently and needs vector software for getting the colors.

---

But yeah, I merge this.

2022-12-31 15:52 UTC, merged