New icon: Rakuten
aegis-icons/aegis-icons pull request #805
Opened 2023-01-15 15:36 UTC by Dampypena

- [x] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site:**
https://fr.shopping.rakuten.com/

**Proof of the Aegis-compatible 2FA:**

![RakutenOTP](https://user-images.githubusercontent.com/7217430/212549965-a9aa5f98-35bb-4347-8e42-09b4811bb0ae.png)

**Logo / icon info:**
I got the [logo](https://www.facebook.com/RakutenFrance/photos/a.463230559904/10158639728074905/ ) from their [Facebook page](https://www.facebook.com/RakutenFrance/) and I converted it in SVG with [Convertio](https://convertio.co/png-svg/). I had to do small modifications in Inkscape to have a clean logo.

**Background color info:**
The color was taken from the header of the [website](https://fr.shopping.rakuten.com/) `#bf0000`

![image](https://user-images.githubusercontent.com/7217430/212550315-f4ee9d17-5fca-4e7b-b467-7984a553f483.png)

2023-01-15 18:32 UTC, krisu5 requested changes
> I got the [logo](https://www.facebook.com/RakutenFrance/photos/a.463230559904/10158639728074905/) from their [Facebook page](https://www.facebook.com/RakutenFrance/) and I converted it in SVG with [Convertio](https://convertio.co/png-svg/). I had to do small modifications in Inkscape to have a clean logo.

Replace the logo with SVG from [press page](https://fr.shopping.rakuten.com/rakuten-france-brand/) ("Télécharger notre logo" button, in the ZIP's `/RVB/RED` folder).

Also use full logo, don't make it "favicon-like" / "social media avatar-like".

> The color was taken from the header of the [website](https://fr.shopping.rakuten.com/) #bf0000

Use logo's color.

2023-01-22 23:44 UTC, Sami32 commented
https://corp.rakuten.co.jp/assets/img/common/logo.svg

2023-01-29 17:05 UTC, Dampypena commented
I replaced the logo with https://corp.rakuten.co.jp/assets/img/common/logo.svg.

The logo color is also `#bf0000`, so I did not changed it.

2023-01-30 15:44 UTC, krisu5 approved these changes

2023-01-30 15:58 UTC, merged