New icon: La Poste (France)
aegis-icons/aegis-icons pull request #824
Opened 2023-01-28 21:11 UTC by Paragoumba

- [x] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site:** [laposte.fr](https://moncompte.laposte.fr/moncompte-auth/auth/realms/mon-compte/protocol/openid-connect/auth)

**Proof of the Aegis-compatible 2FA:** [2FA Doc](https://aide.laposte.fr/contenu/comment-activer-la-double-authentification)

**Logo / icon info:** [Direct URL of the logo file](https://moncompte.laposte.fr/moncompte-auth/auth/resources/u8w7j/login/moncompte/dist/assets/default-logo.b26e0bd7a1ee5e08c5635de46bce26b7.svg)

**Background color info:** 
Took the most dark yellow from the gradient of the logo [here](https://www.laposte.fr/)
![image](https://user-images.githubusercontent.com/22895992/215291198-c0618c0d-dfd3-4b08-b27c-beffa0f6fac2.png)

Background color is from the logo (`#e6af32`).

How should post services from different countries with the same name be handled? For example, French and Swiss post services are both named "La Poste" but with different logos and are entirely separate entities.

For now I added the country between parentheses after the name.

2023-01-28 22:04 UTC, krisu5 commented
> How should post services from different countries with the same name be handled? For example, French and Swiss post services are both named "La Poste" but with different logos and are entirely separate entities.

We don't have guideline for that because it hasn't happen. For now it's non-issue.

2023-01-28 22:13 UTC, krisu5 requested changes
Remove guides and compress the SVG

2023-01-28 22:30 UTC, Paragoumba commented
Should all be fixed now

2023-01-29 11:47 UTC, krisu5 approved these changes

2023-01-29 11:58 UTC, merged