New icon: Duo
aegis-icons/aegis-icons pull request #889
Opened 2023-04-06 20:29 UTC by danielrparks

- [x] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site:** https://duo.com/

**Proof of the Aegis-compatible 2FA:** https://github.com/beemdevelopment/Aegis/blob/master/app/src/main/java/com/beemdevelopment/aegis/importers/DuoImporter.java

**Logo / icon info:** The press kit is down, so I downloaded the logo from [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Duo_Logo_Green.svg).

**Background color info:** The color is `#6bbf4e` from the trial button on their website ([a.btn--green](https://duo.com/))

2023-04-08 13:46 UTC, krisu5 commented
> Proof of the Aegis-compatible 2FA: https://github.com/beemdevelopment/Aegis/blob/master/app/src/main/java/com/beemdevelopment/aegis/importers/DuoImporter.java

Okay it's importer, but it not really proof that Duo icon is needed for Aegis. Since in my knowledge it just imports the TOTP seeds from Duo.

Please explain your reason better or give me proper proof as stated on PR template.

2023-04-08 13:51 UTC, krisu5 requested changes
> Background color info: The color is #6bbf4e from the trial button on their website ([a.btn--green](https://duo.com/))

Use background color of the logo.

2023-05-06 08:05 UTC, krisu5 commented
Closed as stale.

2026-02-21 06:32 UTC, Goldmaster commented
Hi there,

I have taken over the aegis icons project and currently going over closed merge requests. Duo itself is a 2fa tool but in order to merge this, I would need proof that duo accounts have totp 2fa support.

Please DO NOT include personal information or the qr code for enabling 2fa support as anyone who scans will get your totp seed.

2026-03-07 21:52 UTC, Goldmaster commented
To keep the project true to the original mission, Duo admin account does not seam to support TOTP according to here https://duo.com/docs/administration#admin-panel-overview as a result this will have to be closed. If duo do add TOTP support to the admin panel in the future, please feel free to reopen.

2026-03-07 21:52 UTC, closed without merging