New icon: Ed
aegis-icons/aegis-icons pull request #890
Opened 2023-04-06 22:26 UTC by danielrparks

- [x] I have carefully read and followed [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) document.

**URL of the site:** https://edstem.org/

**Proof of the Aegis-compatible 2FA:** 
![image](https://user-images.githubusercontent.com/42898924/230504630-237cab0c-3716-476d-8e83-1d63d5e11a97.png)

**Logo / icon info:** Adapted from logo on [login screen](https://edstem.org/us/login), selector `img.start-ed-icon`

**Background color info:** The background is sampled from the middle of the gradient on the original icon.

2023-04-07 06:16 UTC, krisu5 commented
> **Proof of the Aegis-compatible 2FA:** [image](https://user-images.githubusercontent.com/42898924/230504630-237cab0c-3716-476d-8e83-1d63d5e11a97.png)

Proof is not good enough, as stated on the issue form:

> Documentation link or screenshot should clearly mention that 2FA is (T)OTP / HOTP or any mobile 2FA app (eg. Google Authenticator, Microsoft Authenticator, LastPass Authenticator etc.) or show section of the 2FA setup page with *(censored)* OTP 2FA QR code image. **Otherwise we cannot be sure if 2FA actually is compatible for Aegis.**

Please provide screenshot or documentation link that resolves this issue.

2023-04-07 17:04 UTC, danielrparks commented
Haha, I was hoping I wouldn't have to go through the process of re-enrolling.

Here's a screenshot of the actual 2fa modal (not the original qr code):
![image](https://user-images.githubusercontent.com/42898924/230624887-c10f7d45-dc3c-4dfa-a7b6-48e334b735eb.png)

2023-04-08 13:56 UTC, krisu5 requested changes
Include the rounded square from the logo (make holes to it with the letters).

2023-05-06 08:06 UTC, krisu5 commented
Closed as stale.

2026-03-07 21:45 UTC, merged